name: Build and Push Docker Image

on:
  push:
    branches:
      - main

env:
  IMAGE_VERSION: "0.0.10"
  IMAGE_NAME: "sigma-farm-image"
  IMAGE_USERNAME: "klementus"

jobs:
  build_and_push:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Login to Docker Hub
      run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_LOGIN }}" --password-stdin

    - name: Build and Push Docker Image
      run: |
        docker build -t ${IMAGE_USERNAME}/${IMAGE_NAME}:${IMAGE_VERSION} .
        docker push ${IMAGE_USERNAME}/${IMAGE_NAME}:${IMAGE_VERSION}
    
