name: Build and Push Docker Image

on:
  push:
    branches:
      - main

env:
  IMAGE_VERSION: "0.0.8"

jobs:
  build_and_push:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Login to Docker Hub
      run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_LOGIN }}" --password-stdin

    - name: Build and Push Docker Image
      run: |
        docker build -t klementus/sigma-farm-image:${IMAGE_VERSION} .
        docker push klementus/sigma-farm-image:${IMAGE_VERSION}
